import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { PredictionContextProvider } from "@/coontext/prediction";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PredictionContextProvider>
        <body className={`${inter.className} p-8 lg:p-24 max-w-8xl mx-auto`}>
          {children}
        </body>
      </PredictionContextProvider>
    </html>
  );
}
